package com.myapp.struts;
// Generated 1 Mar, 2019 3:10:10 PM by Hibernate Tools 4.3.1



/**
 * Academic generated by hbm2java
 */
public class Academic  extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String regcode;
     private String course;
     private Integer year;
     private String institute;
     private String board;
     private Integer cgpa;

    public Academic() {
    }

	
    public Academic(String regcode) {
        this.regcode = regcode;
    }
    public Academic(String regcode, String course, Integer year, String institute, String board, Integer cgpa) {
       this.regcode = regcode;
       this.course = course;
       this.year = year;
       this.institute = institute;
       this.board = board;
       this.cgpa = cgpa;
    }
   
    public String getRegcode() {
        return this.regcode;
    }
    
    public void setRegcode(String regcode) {
        this.regcode = regcode;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public String getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(String institute) {
        this.institute = institute;
    }
    public String getBoard() {
        return this.board;
    }
    
    public void setBoard(String board) {
        this.board = board;
    }
    public Integer getCgpa() {
        return this.cgpa;
    }
    
    public void setCgpa(Integer cgpa) {
        this.cgpa = cgpa;
    }




}


