package com.myapp.struts;
// Generated 1 Mar, 2019 3:10:10 PM by Hibernate Tools 4.3.1



/**
 * Internships generated by hbm2java
 */
public class Internships  extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String regcode;
     private Integer num;
     private String info;

    public Internships() {
    }

	
    public Internships(String regcode) {
        this.regcode = regcode;
    }
    public Internships(String regcode, Integer num, String info) {
       this.regcode = regcode;
       this.num = num;
       this.info = info;
    }
   
    public String getRegcode() {
        return this.regcode;
    }
    
    public void setRegcode(String regcode) {
        this.regcode = regcode;
    }
    public Integer getNum() {
        return this.num;
    }
    
    public void setNum(Integer num) {
        this.num = num;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


