package com.myapp.struts;

//package com.myapp.struts;
// Generated 1 Mar, 2019 3:10:10 PM by Hibernate Tools 4.3.1

/**
 * Personal generated by hbm2java
 */
public class Personal extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private String regcode;
     private String rollno;
     private String name;
     private String dob;
     private String email;
     private String address;
     private String nationality;
     private Long mobile;

    public Personal() {
    }

	
    public Personal(String regcode) {
        this.regcode = regcode;
    }
    public Personal(String regcode, String rollno, String name, String dob, String email, String address, String nationality, Long mobile) {
       this.regcode = regcode;
       this.rollno = rollno;
       this.name = name;
       this.dob = dob;
       this.email = email;
       this.address = address;
       this.nationality = nationality;
       this.mobile = mobile;
    }
   
    public String getRegcode() {
        return this.regcode;
    }
    
    public void setRegcode(String regcode) {
        this.regcode = regcode;
    }
    public String getRollno() {
        return this.rollno;
    }
    
    public void setRollno(String rollno) {
        this.rollno = rollno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public Long getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Long mobile) {
        this.mobile = mobile;
    }




}


