package com.myapp.struts;
// Generated 1 Mar, 2019 3:10:10 PM by Hibernate Tools 4.3.1



/**
 * Workexp generated by hbm2java
 */
public class Workexp extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String regcode;
     private Integer duration;
     private String company;

    public Workexp() {
    }

	
    public Workexp(String regcode) {
        this.regcode = regcode;
    }
    public Workexp(String regcode, Integer duration, String company) {
       this.regcode = regcode;
       this.duration = duration;
       this.company = company;
    }
   
    public String getRegcode() {
        return this.regcode;
    }
    
    public void setRegcode(String regcode) {
        this.regcode = regcode;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }




}


